### ISSUE TITLE
Change link into github repo

### ISSUE THREAD

**Issue by tsrandrei** [symbiod/symbiod#547]
**Value**
Describe how the requested changes will affect the system. What profit does it bring?
- The link :  https://symbiod.org/ doesn't have a redirect to https://www.symbiod.org/ 

**Possible solution**
- Change the link into the github repo or do a redirect from https://symbiod.org/

**Comment by khusnetdinov** [comment]
👍

**Comment by khusnetdinov** [comment]
Welcome for PR )

**Comment by tsrandrei** [comment]
@khusnetdinov On the way...noob here

**Comment by tsrandrei** [comment]
PR #548. Hope I've done all right. Do you will change the link in the description of the project?

**Comment by Mehonoshin** [comment]
Merged
