### ISSUE TITLE
[BUG] Can't register myself as organisation

### ISSUE THREAD

**Issue by davydovanton** [symbiod/symbiod#570]
**Value**
Hey, I want to register as a organisation but got this error
![screenshot 2019-02-18 18 54 21](https://user-images.githubusercontent.com/1147484/52962631-cab9a180-33ae-11e9-9ffb-ff09f468cba1.jpeg)

**Possible solution**
Have no idea

**Steps for reproduction**
1. Just open this page: https://www.symbiod.org/idea/wizard/registrations/new
2. Fill all fields and click `sign up`
3. PROFIT

**Comment by khusnetdinov** [comment]
@davydovanton Got it.

**Comment by Mehonoshin** [comment]
@davydovanton thanks for report!
Most probably the reason it that we forgot to change recaptcha settings after moving to the new domain name.
We'll fix that ASAP

**Comment by Mehonoshin** [comment]
@davydovanton it should work now. Feel free to reopen the issue if you have any troubles.
